# Generated by Django 5.2.6 on 2025-09-13 04:19

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created'], 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-created'], 'verbose_name': 'Form Submission', 'verbose_name_plural': 'Form Submissions'},
        ),
        migrations.RemoveField(
            model_name='form',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='form',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
