# Generated by Django 5.2.6 on 2025-09-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_alter_form_options_alter_formsubmission_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
